"""empty message

Revision ID: c2245c70c574
Revises: 0d4057e59ff2
Create Date: 2022-01-04 09:19:04.319594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2245c70c574'
down_revision = '0d4057e59ff2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('kennel_name', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'kennel_name')
    # ### end Alembic commands ###
