"""empty message

Revision ID: 005335d6cef0
Revises: c2245c70c574
Create Date: 2022-01-04 09:30:14.266635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '005335d6cef0'
down_revision = 'c2245c70c574'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kennels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('cleanliness', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kennels')
    # ### end Alembic commands ###
