"""empty message

Revision ID: 83db98dedf0e
Revises: d82a1d0da566
Create Date: 2022-01-05 07:06:13.689319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83db98dedf0e'
down_revision = 'd82a1d0da566'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('breeds', sa.Column('population', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('breeds', 'population')
    # ### end Alembic commands ###
