"""empty message

Revision ID: 23ca625e3a60
Revises: 7ba091745c5e
Create Date: 2022-01-05 07:33:33.669440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23ca625e3a60'
down_revision = '7ba091745c5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('breeds', sa.Column('breed_group', sa.Integer(), nullable=False))
    op.add_column('breeds', sa.Column('personality', sa.String(), nullable=False))
    op.add_column('breeds', sa.Column('avg_height', sa.JSON(), nullable=False))
    op.add_column('breeds', sa.Column('avg_weight', sa.JSON(), nullable=False))
    op.add_column('breeds', sa.Column('avg_life_exp', sa.String(), nullable=False))
    op.add_column('breeds', sa.Column('breed_video', sa.String(), nullable=False))
    op.add_column('breeds', sa.Column('description', sa.Text(), nullable=False))
    op.drop_constraint('breeds_group_id_fkey', 'breeds', type_='foreignkey')
    op.create_foreign_key(None, 'breeds', 'groups', ['breed_group'], ['id'])
    op.drop_column('breeds', 'group_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('breeds', sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'breeds', type_='foreignkey')
    op.create_foreign_key('breeds_group_id_fkey', 'breeds', 'groups', ['group_id'], ['id'])
    op.drop_column('breeds', 'description')
    op.drop_column('breeds', 'breed_video')
    op.drop_column('breeds', 'avg_life_exp')
    op.drop_column('breeds', 'avg_weight')
    op.drop_column('breeds', 'avg_height')
    op.drop_column('breeds', 'personality')
    op.drop_column('breeds', 'breed_group')
    # ### end Alembic commands ###
