"""empty message

Revision ID: 7ba091745c5e
Revises: 83db98dedf0e
Create Date: 2022-01-05 07:07:16.925998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ba091745c5e'
down_revision = '83db98dedf0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('breeds', sa.Column('group_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'breeds', 'groups', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'breeds', type_='foreignkey')
    op.drop_column('breeds', 'group_id')
    # ### end Alembic commands ###
