"""empty message

Revision ID: 0c4043c61812
Revises: 317490e45c24
Create Date: 2022-01-05 07:01:51.094296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c4043c61812'
down_revision = '317490e45c24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('breeds', sa.Column('population', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('breeds', 'population')
    # ### end Alembic commands ###
