"""empty message

Revision ID: 317490e45c24
Revises: 574346174449
Create Date: 2022-01-05 07:01:38.372443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '317490e45c24'
down_revision = '574346174449'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('breeds', 'population')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('breeds', sa.Column('population', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
