"""empty message

Revision ID: 66f1678c908a
Revises: 23ca625e3a60
Create Date: 2022-01-05 07:35:05.356678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66f1678c908a'
down_revision = '23ca625e3a60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('description', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'description')
    # ### end Alembic commands ###
