"""empty message

Revision ID: 7dd59895ecf9
Revises: 005335d6cef0
Create Date: 2022-01-04 09:34:18.011731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dd59895ecf9'
down_revision = '005335d6cef0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kennels', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'kennels', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'kennels', type_='foreignkey')
    op.drop_column('kennels', 'user_id')
    # ### end Alembic commands ###
