"""empty message

Revision ID: 574346174449
Revises: c8f8f1fa6bea
Create Date: 2022-01-05 06:58:53.315339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '574346174449'
down_revision = 'c8f8f1fa6bea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dogs', sa.Column('breed', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'dogs', 'breeds', ['breed'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dogs', type_='foreignkey')
    op.drop_column('dogs', 'breed')
    # ### end Alembic commands ###
